//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission_table
    {
        public int id_table { get; set; }
        public int id_position { get; set; }
        public bool rule_update { get; set; }
        public bool rule_delete { get; set; }
        public bool rule_insert { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual table table { get; set; }
    }
}
