//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public System.DateTime date { get; set; }
        public int id_dish { get; set; }
        public int price1 { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
